
node {
   stage 'Build'
   		echo 'Building the app'
   		sh 'pwd'
   		sh 'ls'
   		sh 'cd microservice/app'
   		sh 'sudo docker rmi localhost:5000/app || ls'
   		sh 'sudo docker rmi $(sudo docker images -f "dangling=true" -q) || ls'
   		sh 'sudo docker build -t app .'
   		sh 'sudo docker tag -f app localhost:5000/app'
   		sh 'sudo docker push localhost:5000/app'
   stage 'Staging Deployment'
   		echo 'Hello World 2'
        sh 'ls'
   stage 'Acceptance Test'
   		echo 'Hello World 2'
        sh 'ls'
   stage 'Production Deployment'
   		echo 'Hello World 2'
        sh 'ls'
}